// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/22/2025, 10:22:56 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/2022/Desktop/D-House-Fruit/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/2022/Desktop/D-House-Fruit/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/2022/Desktop/D-House-Fruit/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/2022/Desktop/D-House-Fruit/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/2022/Desktop/D-House-Fruit/plugins/**/*.{js,ts,mjs}","C:/Users/2022/Desktop/D-House-Fruit/composables/**/*.{js,ts,mjs}","C:/Users/2022/Desktop/D-House-Fruit/utils/**/*.{js,ts,mjs}","C:/Users/2022/Desktop/D-House-Fruit/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/2022/Desktop/D-House-Fruit/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/2022/Desktop/D-House-Fruit/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/2022/Desktop/D-House-Fruit/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;